### ISSUE TITLE
Don't run as user

### ISSUE THREAD

**Issue by oliv3r** [curl/curl-docker#22]
Currently, we see in  https://github.com/curl/curl-docker/blob/master/alpine/latest/Dockerfile#L77 that the docker container is being run as a specific user, while from a security point of view, this sounds sensible initially, it is actually wrong from the docker point of view for the following reasons:
* If the container is to be run as root (for whatever reason the user has) has to be forced with --user 0:0, which is very counter intuitive compared to other docker containers.
* If a user of the container wishes to use it as its base for things (for example to add git, by doing apk add git) this is no longer possible (permission denied). This especially breaks behavior for CI systems, such as gitlab for example, where one would pick this container as its base image, and then add stuff on top of it for their use

It's best to follow standard docker practices, by not forcing some arbitrary user in the default configuration.

**Comment by xquery** [comment]
unsure what the right answer is here - I am aware of standard practice but was hesitant to emulate what I see as bad security practice.

We have had 10m+ pulls on the image so far (most of which I gather are CI related) with no complaints that this decision has made it awkward for anyone else. Considering this I am not motivated to make a change based on a single (albeit respected) request for enhancement.

Will keep this open and ask more broadly to see if anyone else has opinions.

**Comment by oliv3r** [comment]
Well it really depends what is' being used for of course; but what you consider bad security practise (I do not disagree) is considered the 'normal' in the docker world. I do hope the goal is, to eventually have this image become one of the 'official' images. e.g. hub.docker.com/_/curl right? And if that's the case, I guess following standard practices is expected.

That said, I understand this is just my report and I'm just one mouth :)

Now, how do you suggest to work around the CI issue, where we want to add stuff to the CI image. e.g.
`apk add <package` won't work, but someone may want to really just use the curl image and work around a (temporary short coming)? This is of course not possible. What I suspect others do, is they just create their own images in this case (People are lazy and sloppy) so they probably just do 'image: alpine:latest' and then `apk add curl`
In my specific case, gitlab currently does not expose the tag message (like it does for commit messages) so I needed to (temporarly) add git to my step that only relies on curl, so that I could obtain the tag message. Something stupid and trivial, but also not something I wish to build a new container for.

If you are very ademant about this security 'feature' (which again, I do think is wise), you intend to also pursue this with upstream docker as a best practice for 'official' images?

**Comment by xquery** [comment]
The current image is conservative by design  ... being an initial release we wanted to get some feedback on usage before making assumptions. It is not intentional to make it harder to integrate and your experience no doubt mimics others.

For now I am going to bundle this enhancement along with #23 and start discussing with docker hub what it might take to get curl included in their official images.

**Comment by hubgit** [comment]
This caused a problem when using `curlimages/curl` as the base for a Docker GitHub Action, which needs to be run as root so it can write to the mounted directory.

https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#filesystems-on-github-hosted-runners

> GitHub Actions must be run by the default Docker user (root). Ensure your Dockerfile does not set the USER instruction, otherwise you will not be able to access GITHUB_WORKSPACE.

I was able to work around this by adding `USER root` to the GitHub Action's Dockerfile.

**Comment by Lewiscowles1986** [comment]
@oliv3r you should not be inheriting this image. Think of it like a final class.

I feel like the docs should call-out not inheriting this image, but composing in a containing domain or category, or in extreme cases, forking.

This is great documentation on a release of curl within docker. I watched the DockerCon Live presentation at https://www.youtube.com/watch?v=lZreoYmoMHM and felt very strongly that bundling or extending this with `jq` for example, is not an orthagonal system. It's not what docker is for. Such complexity is really VM territory, and a VM could contain docker and pull this and `jq` and pipe the output of curl to jq, or use a real file or ENV as intermediary.

**Comment by xquery** [comment]
after this thread and consulting with a few ppl (during dockercon) ... going to close this. It maybe that work we might do in making a proper base image for submission to docker standard library addresses this.

**Comment by oliv3r** [comment]
@xquery sorry for not getting back to this sooner :) i had forgotten about it; but solving this in 'getting it as a official library' is the best way forward, where this discussion is probably held equally :)

As for @Lewiscowles1986 I'm sure that's a awesome docker goal, but that will takes YEARS to accomplish. Many many pipelines will break if dockers says 'from now on, your containers are not running as root by default. They should have thought of this early on :)

As for extending things, sometimes, it does simply make sense to extend things. As i said above, sometimes, you simply want to add a simple tool to an existing image. This is also why many 'tool based' containers offer 2 flavors!

one is a `FROM scratch` kind of deal, where you truly only get the binary + its dependencies, which can indeed only run as root, as it's next to impossible to extend. And secondly, a 'alpine' or 'debian' variant, where you do get a shell, you do get the capability to do slightly more. This gives the _freedom_ to the user to choose what he needs or wants to do. My peeve this this issue initially was, that you are _removing_ the choice from the user, because 'but I think this is a good idea, I won't want you to add stuff to my container'.

Now as the issue is closed, and this is solved in the 'official effort' we can let it rest :)

P.S. Maybe in the future we get a third kind of 'common image flavor', where you get a 'statically compiled sh' only added, to please CI's, as those tend to need something just slightly more then only the binary. So you'd end up with sh + bin only to offer a minimal secure container :) 'Dash' statically linked against klibc would be such a thing ...

**Comment by Ark-kun** [comment]
This image cannot write to any mounted volume =(( I had to spend hours trying to understand what's going on why one of the components were failing while the rest worked as expected.

I've explicitly mounted the volume to the pod. That's my explicit choice.

Why go out of your way to limit the usability of the image by preventing it from writing to mounted volumes?

**Comment by xquery** [comment]
Sorry to hear of difficulties ... we do document that the image defines and uses a curl user but I suspect that is cold comfort for you after spending hours trying to figure things out ... to be clear having a curl user is an explicit design choice. 

Running an app as root is inherently dangerous in any computing context ... we are especially sensitive due to the widespread usage of curlimages/curl - at over 800m pulls!  https://hub.docker.com/v2/repositories/curlimages/ ... with very few complaints.

When a choice has to be made between 'ease of use' vs security - curl will always opt for the later.

I will try to make this more explicit in the various READMEs and you are always free to create your own image using curlimages/curl as base to do what you want.

**Comment by Lewiscowles1986** [comment]
@Ark-kun you can write to a volume with the same `UID` or `GID` if permissions are set correctly on the host.

If Docker generates the directory, it may unfortunately create it owned by root, but that is a Docker problem, and one that can be overcome by you manually creating the directory.

`chown` and `chmod` will allow you to take explicit control of file permissions. I Would suggest ensuring either `UID`, `GID` or both match this image user.

**Comment by Ark-kun** [comment]
@xquery 
Thank you for your response. I apologize for venting my frustration.
I understand that having a popular official image leads to people using it in a way that might be far outside of what you intended (e.g. using it in Kubernetes and Kubeflow Pipelines [components](https://github.com/kubeflow/pipelines/blob/master/components/datasets/Chicago_Taxi_Trips/component.yaml)).

On  a high-level the difference is that we cannot pipe the data out of the container immediately, so the data is downloaded to a file. And getting files out of a container is pretty cumbersome even in best cases.

@Lewiscowles1986 
>you can write to a volume with the same UID or GID if permissions are set correctly on the host.

One additional issue is that using the same shared volume with multiple images that use different users is a nightmare.
The fault is probably more in docker or Kubernetes for allowing this mess rather than in this container image.

>chown and chmod will allow you to take explicit control of file permissions. I Would suggest ensuring either UID, GID or both match this image user.

Thank you for the suggestion, but I'm not sure this is possible. The volume is dynamically provisioned by Kubernetes when I [create a PersistentVolumeClaim](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolumeclaim). I just tell the size I need. I then [mount that PVC as a volume to a Kubernetes Pod](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-pod). At no point I'm specifying UID or GID. Also I'm mounting a volume sub-path that does not even exist at the time of mounting (probably inherited form the volume root). This gets me wondering which part of the system creates the actual filesystem in that volume.

Thank you.

**Comment by Lewiscowles1986** [comment]
@Ark-kun https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod

**Comment by Ark-kun** [comment]
Thank you, Lewis. We'll try that.

**Comment by im-n1** [comment]
Just ran into this. The simplest solution is use `alpine` image and install curl with `apk add curl`.
