### ISSUE TITLE
Travis CI changes

### ISSUE THREAD

**Issue by J0WI** [curl/curl-docker#46]
Travis CI changed their infrastructure and policies for open source repos:
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

It seems that they started to limit the concurrent builds for open source projects recently: https://www.traviscistatus.com/

Tests will stop working completely by the end of the year:

> We are announcing that travis-ci.org will be officially closed down completely no later than December 31st, 2020

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by xquery** [comment]
travis still works - we will try to migrate to 'something else' before 7.76.0 release

**Comment by xquery** [comment]
May 2021 is end of life for travis ... going to have to get on my skates and migrate

**Comment by mback2k** [comment]
Seems like you could just link up to .com instead:

https://blog.travis-ci.com/2021-05-07-orgshutdown

**Comment by dfandrich** [comment]
But, .com isn't free. Once you use up your trial minutes, they're gone.

**Comment by xquery** [comment]
I was of the mind that we move off travis  and consider other options ( github actions, dockerhub ) ..... open to any other suggestions.

**Comment by mback2k** [comment]
> But, .com isn't free. Once you use up your trial minutes, they're gone.

Yes, but according to their welcome e-mail you can e-mail them to get free OSS credits for public open source projects. I just did that for the libssh2 org, let's see if it works out. For the curl main repository it would be quite sad if we could not spread the builds also to Travis-CI any longer, but I guess for curl-docker or curl-for-win, it would not be that big of a problem.

@bagder and I spoke in IRC about the general migration for the curl org, let's see how that will turn out.

**Comment by mback2k** [comment]
I just received the list of requirements to get the OSS plan and it looks like curl will not be able to get it due to the last 2 rules:

> - You are a project lead or regular committer (latest commit in the last month)
> - Project must be at least 3 months old and is in active development (with regular commits and activity)
> - Project meets the [OSD](https://opensource.org/docs/osd) specification
> - Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)
> - Project can not provide commercial services or distribute paid versions of the software

**Comment by bagder** [comment]
> I can highly recommend (in order of personal preference as of today) GitHub Actions

The last week or so, GitHub actions have been so slow they've been more or less dead (>24 hours to complete a single PR round). We've had to merge many PRs with less CIs because of this. I truly hope this is a temporary slow-down and that they will bounce back, otherwise we will have problems going forward.

> it looks like curl will not be able to get it due to the last 2 rules

So Travis goes from recently having given us extra-power to not even qualifying us as legible for the open source tier. It looks like our CI situation is quickly deteriorating... :cry:

**Comment by bagder** [comment]
I filed https://github.com/curl/curl/issues/7150

**Comment by mback2k** [comment]
Regarding performance of GitHub Actions: does this affect all types of builds or just macOS? That one is always being limited on all CI platforms, e.g. GitHub, Azure, Cirrus and more use MacStadium for that and resources are limited due to the requirement of running on real Mac hardware.

**Comment by xquery** [comment]
initially we are going to migrate to zuul - as per parent project

https://github.com/curl/curl/blob/master/zuul.d/jobs.yaml

**Comment by albinvass** [comment]
@xquery I pushed https://github.com/curl/curl-docker/pull/57 which should add a job to build the container image. However I think it is currently not triggering zuul since master is not a protected branch.
We're currently excluding all unprotected branches since otherwise it would be possible to access secrets (if there were any stored in the project). So to get things running we need to either not exclude unprotected branches or make master a protected branch. I think the second option is to be preferred. :)

**Comment by albinvass** [comment]
I got some help from @bagder to fix that.
Looks like #57 is working with a slight modification to remove the tty usage of the test.

**Comment by xquery** [comment]
we use zuul now
